<?php
/**
 * TL_ROOT/system/modules/log_accounts/languages/lv/modules.php 
 * 
 * Contao extension: log_accounts 1.0.0 stable 
 * Latvian translation file 
 * 
 * Copyright : &copy; 2010 Paolo Battistella 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Paolo Battistella (paplo) 
 * Translator: Maris Celmins (warrior), http://www.bauskasbiblioteka.lv 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['log_users']['0'] = "Lietotāju statistika";
$GLOBALS['TL_LANG']['MOD']['log_users']['1'] = "Skatīt lietotāja statistiku (backend lietotājiem).";
$GLOBALS['TL_LANG']['MOD']['log_members']['0'] = "Dalībnieku statistika";
$GLOBALS['TL_LANG']['MOD']['log_members']['1'] = "Skatīt lietotāja statistiku (frontend dalībniekiem).";
 
?>
